name: .NET Core Test and Publish

on:
  push:
    branches: [master]

env:
  DOTNET_VERSION: 8.0.202

jobs:

  Test:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: |
        dotnet build \
        --configuration Release
        --output ./bin

    - name: Test
      if: ${{ matrix.os }} == 'windows-latest'
      working-directory: ./bin
      run: |
        ./TestSHA3.exe

    - name: Test
      if: ${{ matrix.os }} != 'windows-latest'
      working-directory: ./bin
      run: |
        ./TestSHA3
