name: .NET Core Test and Publish

on:
  push:
    branches: [master]

env:
  DOTNET_VERSION: 8.0.202

jobs:

  Test:
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Test
      continue-on-error: true
      run: |
        dotnet run --project ./src/TestSHA3/TestSHA3.csproj
